//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.PickUpPoint = new HashSet<PickUpPoint>();
        }
    
        public int Id { get; set; }
        public string CityName { get; set; }
    
        public virtual ICollection<PickUpPoint> PickUpPoint { get; set; }
    }
}
