//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orderr
    {
        public int id { get; set; }
        public Nullable<System.DateTime> orderDate { get; set; }
        public Nullable<System.DateTime> arriveDate { get; set; }
        public Nullable<int> adressId { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> code { get; set; }
        public Nullable<int> statusId { get; set; }
    
        public virtual PickUpPoint PickUpPoint { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
