//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickUpPoint
    {
        public PickUpPoint()
        {
            this.Orderr = new HashSet<Orderr>();
        }
    
        public int Id { get; set; }
        public Nullable<int> PostCode { get; set; }
        public Nullable<int> CityId { get; set; }
        public string Street { get; set; }
    
        public virtual City City { get; set; }
        public virtual ICollection<Orderr> Orderr { get; set; }
    }
}
